"boa":
  - "packages/boa/**"
  - "example/boa/**"

"build":
  - ".github/**"
  - ".eslintrc.js"
  - ".eslintignore"
  - "package.json"
  - "tsconfig.json"

"cli":
  - "packages/cli/**"

"core":
  - "packages/core/**"

"pipboard":
  - "packages/pipboard-client/*"
  - "packages/pipboard-server/*"

"documentation":
  - "*.md"
  - "docs/**"
  - "typedoc.json"
