package:
  name: nose
  version: 1.3.7

source:
  url: https://pypi.io/packages/source/n/nose/nose-1.3.7.tar.gz
  sha256: f1bffef9cbc82628f6e7d7b40d7e255aefaa1adb6a1b1d26c69a8b79e6208a98

requirements:
  run:
    - setuptools

test:
  imports:
    - nose
